import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `prisma generate` — both `prisma-client` and `prisma-zod-generator`.
    "generated/**",
  ]),
  {
    rules: {
      // CLAUDE.md: `any` is forbidden. Use `unknown` + type guards or a proper type.
      "@typescript-eslint/no-explicit-any": "error",
      // Block `@ts-ignore`, `@ts-nocheck`, `@ts-expect-error` (the latter without a description).
      "@typescript-eslint/ban-ts-comment": "error",
      // Forbid `{ foo: bar } as SomeType` — a common source of silent bugs. Allow `value as SomeType`.
      "@typescript-eslint/consistent-type-assertions": [
        "error",
        { assertionStyle: "as", objectLiteralTypeAssertions: "never" },
      ],
      // Forbid casting to `unknown` (incl. the `as unknown as T` escape hatch).
      "no-restricted-syntax": [
        "error",
        {
          selector: "TSAsExpression[typeAnnotation.type='TSUnknownKeyword']",
          message:
            "Casting to `unknown` (including `as unknown as T`) is forbidden. Use a proper type guard or define a real type.",
        },
      ],
    },
  },
]);

export default eslintConfig;
